# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org'
platform :ios, '14.1'

target 'iosApp' do
  use_frameworks!
  use_modular_headers!

  pod 'sharedModule', :path => '../sharedModule'
end
